cmake_minimum_required(VERSION 3.25)
include("${CMAKE_CURRENT_LIST_DIR}/../../cmake/Features.cmake")
miracle_register_build_feature(NAME a DEFAULT DEPENDS b)
miracle_register_build_feature(NAME b DEPENDS c)
miracle_register_build_feature(NAME c DEPENDS a)
miracle_configure_build_features()
